const CHANNEL_SOCKET_EVENTS = {
  // pre defined
  CONNECTION: "connection",
  DISCONNECT: "disconnect",

  // catches

  // emits
  CONNECTED: "CONNECTED",

  // req - res
  REQ_SPACE_LIST: "REQ_SPACE_LIST",
  RES_SPACE_LIST: "RES_SPACE_LIST",

  REQ_CREATE_CONVERSATION: "REQ_CREATE_CONVERSATION",
  RES_CREATE_CONVERSATION: "RES_CREATE_CONVERSATION",

  // LOGGER
  LOGGER: "LOGGER",
};

module.exports = CHANNEL_SOCKET_EVENTS;
